#!/bin/bash
set -e

# Note: $POSTGRES_USER is set to the value 'postgres', the image's default.
# It is different from $PG_USERNAME, which is set on start-up by docker
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE ROLE $PG_USERNAME;
  ALTER ROLE $PG_USERNAME WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD '$PG_PASSWORD';
  CREATE DATABASE $PG_DATABASE WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';
  ALTER DATABASE $PG_DATABASE OWNER TO $PG_USERNAME;
EOSQL
