name: 'Build LSPD'
description: 'Build LSPD and upload the build artifacts.'
runs:
  using: 'composite'
  steps:
    - name: git checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: build
      run: make release-all
      shell: bash

    - name: upload lspd artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          lspd
          lspd_plugin
