// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: history.proto

package history

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HistoryClient is the client API for History service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryClient interface {
	ExportForwards(ctx context.Context, in *ExportForwardsRequest, opts ...grpc.CallOption) (*ExportForwardsResponse, error)
	ImportExternalForwards(ctx context.Context, in *ImportExternalForwardsRequest, opts ...grpc.CallOption) (*ImportExternalForwardsResponse, error)
}

type historyClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryClient(cc grpc.ClientConnInterface) HistoryClient {
	return &historyClient{cc}
}

func (c *historyClient) ExportForwards(ctx context.Context, in *ExportForwardsRequest, opts ...grpc.CallOption) (*ExportForwardsResponse, error) {
	out := new(ExportForwardsResponse)
	err := c.cc.Invoke(ctx, "/history.History/ExportForwards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyClient) ImportExternalForwards(ctx context.Context, in *ImportExternalForwardsRequest, opts ...grpc.CallOption) (*ImportExternalForwardsResponse, error) {
	out := new(ImportExternalForwardsResponse)
	err := c.cc.Invoke(ctx, "/history.History/ImportExternalForwards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServer is the server API for History service.
// All implementations must embed UnimplementedHistoryServer
// for forward compatibility
type HistoryServer interface {
	ExportForwards(context.Context, *ExportForwardsRequest) (*ExportForwardsResponse, error)
	ImportExternalForwards(context.Context, *ImportExternalForwardsRequest) (*ImportExternalForwardsResponse, error)
	mustEmbedUnimplementedHistoryServer()
}

// UnimplementedHistoryServer must be embedded to have forward compatible implementations.
type UnimplementedHistoryServer struct {
}

func (UnimplementedHistoryServer) ExportForwards(context.Context, *ExportForwardsRequest) (*ExportForwardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportForwards not implemented")
}
func (UnimplementedHistoryServer) ImportExternalForwards(context.Context, *ImportExternalForwardsRequest) (*ImportExternalForwardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportExternalForwards not implemented")
}
func (UnimplementedHistoryServer) mustEmbedUnimplementedHistoryServer() {}

// UnsafeHistoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryServer will
// result in compilation errors.
type UnsafeHistoryServer interface {
	mustEmbedUnimplementedHistoryServer()
}

func RegisterHistoryServer(s grpc.ServiceRegistrar, srv HistoryServer) {
	s.RegisterService(&History_ServiceDesc, srv)
}

func _History_ExportForwards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportForwardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).ExportForwards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/history.History/ExportForwards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).ExportForwards(ctx, req.(*ExportForwardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _History_ImportExternalForwards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportExternalForwardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServer).ImportExternalForwards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/history.History/ImportExternalForwards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServer).ImportExternalForwards(ctx, req.(*ImportExternalForwardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// History_ServiceDesc is the grpc.ServiceDesc for History service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var History_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "history.History",
	HandlerType: (*HistoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportForwards",
			Handler:    _History_ExportForwards_Handler,
		},
		{
			MethodName: "ImportExternalForwards",
			Handler:    _History_ImportExternalForwards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "history.proto",
}
