
services:
  lspd:
    image: lspd
    networks:
      - lspd-pg
      - lspd-cln
    environment:
      # Make sure pg/.env is sourced before executing, or change this line by 
      # copying the specific variables from the pg/.env file
      - DATABASE_URL=postgresql://postgres:postgres@pg
      - NODES=[{"cln":{"pluginAddress":"cln:12312","grpcAddress":"cln:8888","caCert":"/data/.lightning/regtest/ca.pem","clientCert":"/data/.lightning/regtest/client.pem","clientKey":"/data/.lightning/regtest/client-key.pem"}}]
    depends_on:
      - pg
      - cln
    volumes:
      - lightning:/data/.lightning

  pg:
    image: postgres:16
    networks:
      - lspd-pg
    # volumes:
    #   - ./pg/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    restart: always

  cln:
    image: lightningd-lsp
    command:
      --bitcoin-rpcuser=btcuser
      --bitcoin-rpcpassword=btcpass
      --bitcoin-rpcconnect=bitcoind
      --bitcoin-rpcport=18443
      --network=regtest
    networks:
      - cln-bitcoind
      - lspd-cln
    depends_on:
      - bitcoind
    volumes:
      - lightning:/data/.lightning

  bitcoind:
    image: bitcoind
    command:
      -regtest
      -server
      -logtimestamps
      -nolisten
      -addresstype=bech32
      -txindex
      -fallbackfee=0.00000253
      -debug=mempool
      -debug=rpc
      -rpcpassword=btcpass
      -rpcuser=btcuser
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
    networks:
      - cln-bitcoind
  # TODO
  # lnd

networks:
  cln-bitcoind:
  lspd-cln:
  lspd-pg:

volumes:
  lightning: